import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Script from "next/script";
import StripeProvider from "./StripeProvider";
import { Toaster } from 'react-hot-toast';



const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], 
  variable: '--font-poppins',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Estate Atlas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="en">
      <head>
        <Script id="gtm-head" strategy="afterInteractive" dangerouslySetInnerHTML={{
          __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-5C7ZZ676');`
        }} />
      </head>
      <body
        className={poppins.variable}
      >
        <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5C7ZZ676"
        height="0" width="0">
        </iframe>
        </noscript>
        <Script 
        strategy="beforeInteractive"
        src={`https://www.google.com/recaptcha/api.js?render=${process.env.NEXT_PUBLIC_CAPTCHA_SITE_KEY}`}
        />
      
        <Providers>
           <StripeProvider>
          <main className="min-h-screen">
            {children}
          </main>
          <Toaster position="top-right" reverseOrder={false} /> 
          </StripeProvider>

        </Providers>
      </body>
    </html>
  );
}
